# Generated by Django 3.0 on 2019-12-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacebookGoogleAuth', '0002_auto_20191213_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
