# Generated by Django 3.0 on 2019-12-13 11:24

import FacebookGoogleAuth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacebookGoogleAuth', '0003_auto_20191213_1419'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', FacebookGoogleAuth.models.UserManager()),
            ],
        ),
    ]
