# Generated by Django 3.0 on 2019-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacebookGoogleAuth', '0004_auto_20191213_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
